puts "Creating seeds 🌱..."

U1 = User.create!(user_name: "KunElite2022", password: "ilovepasta12", date_of_birth: "10/16/1999", age: 23, pronouns: "he/him", bio: "Cybersecurity | Dog-Lover 🐕 | Based in Atlanta, GA", profile_pic_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Ficon-icons.com%2Ficon%2Fbatman-avatar%2F90804&psig=AOvVaw031kPU6YrsWK86uQPcFW-x&ust=1669334215379000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCNDo69nAxfsCFQAAAAAdAAAAABAJ")
U2 = User.create!(user_name: "TouRine", password: "ilikepizza", date_of_birth: "03/21/2000", age: 22, pronouns: "he/him", bio: "Hiya! 👋", profile_pic_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsmilebrightfamilydentistry.com%2Ftestimonials%2F&psig=AOvVaw031kPU6YrsWK86uQPcFW-x&ust=1669334215379000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCNDo69nAxfsCFQAAAAAdAAAAABAT")
U3 = User.create!(user_name: "Chlomoney", password: "chloelovesmonay", date_of_birth: "05/02/2002", age: 20, pronouns: "she/her", bio: "What's up guyssss! Future Software Developer @ Flatiron School #goflatiron #happycoding! 👩‍💻", profile_pic_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shareicon.net%2Favatar-social-user-woman-profile-829453&psig=AOvVaw031kPU6YrsWK86uQPcFW-x&ust=1669334215379000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCNDo69nAxfsCFQAAAAAdAAAAABAY")
U4 = User.create!(user_name: "TaiLr", password: "ttimestwo", date_of_birth: "07/04/1989", age: 33, pronouns: "he/him", bio: "Sup guys, I love every type of music. Hit me up and listen to my playlist. 😘", profile_pic_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shareicon.net%2Fprofile-avatar-man-user-business-people-boy-771188&psig=AOvVaw031kPU6YrsWK86uQPcFW-x&ust=1669334215379000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCNDo69nAxfsCFQAAAAAdAAAAABAd")

puts "Creating playlists..."

P1 = Playlist.create!(playlist_name: "Mood: Happy")
P2 = Playlist.create!(playlist_name: "Mood: Sad")
P3 = Playlist.create!(playlist_name: "Mood: Angry")
P4 = Playlist.create!(playlist_name: "Mood: Mellow")

puts "Creating genres 🎵..."

G1 = Genre.create(name: "Rap")
G2 = Genre.create(name: "Hip-Hop/R&B")
G3 = Genre.create(name: "Classic Rock")
G4 = Genre.create(name: "Holiday")
G5 = Genre.create(name: "Dance/EDM")
G6 = Genre.create(name: "K-Pop")
G7 = Genre.create(name: "Afrobeat")
G8 = Genre.create(name: "Latin")
G9 = Genre.create(name: "Country")
G10 = Genre.create(name: "Pop")

puts "Creating songs 🎵..."

S1 = Song.create!(name: "Rich Flex", artist: "Drake ft. 21 Savage", url: "https://youtu.be/I4DjHHVHWAE", genre_id: G1.id)
S2 = Song.create!(name: "Super Freaky Girl", artist: "Nicki Minaj", url: "https://youtu.be/j5uAR9w7LBg", genre_id: G2.id)
S3 = Song.create!(name: "Just Wanna Rock", artist: "Lil Uzi Vert", url: "https://youtu.be/UhbixyxgsiU", genre_id: G3.id)
S4 = Song.create!(name: "Tomorrow 2", artist: "GloRilla", url: "https://youtu.be/zwa7NzNBQig", genre_id: G4.id)
S5 = Song.create!(name: "Freestyle", artist: "Lil Baby", url: "https://youtu.be/MHryuYVyHhk", genre_id: G5.id)
S6 = Song.create!(name: "Puffin on Zooties", artist: "Future", url: "https://youtu.be/H8E0WIy_vFc", genre_id: G1.id)
S7 = Song.create!(name: "Hotel Lobby", artist: "Quavo & Takeoff", url: "https://youtu.be/Om0rYw6qzb8", genre_id: G2.id)
S8 = Song.create!(name: "First Day Out", artist: "Tee Grizzley", url: "https://youtu.be/pWh4O6ujK4o", genre_id: G3.id)
S9 = Song.create!(name: "Walk It Talk It", artist: "Migos ft. Drake", url: "https://youtu.be/fGqdIPer-ms", genre_id: G4.id)
S10 = Song.create!(name: "Plug Walk", artist: "Rich the Kid", url: "https://youtu.be/ToY6sjSV8h8", genre_id: G5.id)

S11 = Song.create!(name: "Under the Influence", artist: "Chris Brown", url: "https://youtu.be/pfxyk1glEq4", genre_id: G1.id)
S12 = Song.create!(name: "Shirt", artist: "SZA", url: "https://youtu.be/hdFDrjfW548", genre_id: G2.id)
S13 = Song.create!(name: "All Mine", artist: "Brent Faiyaz", url: "https://youtu.be/CHtfJ-UZJM4", genre_id: G3.id)
S14 = Song.create!(name: "Free Mind", artist: "Tems", url: "https://youtu.be/e8GzTXRAJ30", genre_id: G4.id)
S15 = Song.create!(name: "Hrs and Hrs", artist: "Muni Long", url: "https://youtu.be/okfR_VIbXEQ", genre_id: G5.id)
S16 = Song.create!(name: "Over", artist: "Lucky Daye", url: "https://youtu.be/Ylf8gJQe8So", genre_id: G1.id)
S17 = Song.create!(name: "Say It", artist: "Tory Lanez", url: "https://youtu.be/xUq1rZ7mmns", genre_id: G2.id)
S18 = Song.create!(name: "Don't", artist: "Bryson Tiller", url: "https://youtu.be/d7cVLE4SaN0", genre_id: G3.id)
S19 = Song.create!(name: "Break from Toronoto", artist: "PARTYNEXTDOOR", url: "https://youtu.be/lXYq9ImJIN8", genre_id: G4.id)
S20 = Song.create!(name: "Crew", artist: "Goldlink ft. Brent Faiyaz, Shy Glizzy", url: "https://youtu.be/nhNqbe6QENY", genre_id: G5.id)

S21 = Song.create!(name: "Drogba", artist: "Afro B", url: "https://youtu.be/9YqecbxSr4A", genre_id: G1.id)
S22 = Song.create!(name: "Kontrol", artist: "Maleek Berry", url: "https://youtu.be/Si0ZHJdlu9M", genre_id: G2.id)
S23 = Song.create!(name: "Do Like That", artist: "Koredo Bello", url: "https://youtu.be/hJBi780qFas", genre_id: G3.id)
S24 = Song.create!(name: "Leg Over", artist: "Mr. Eazi", url: "https://youtu.be/v15sS1sL_S4", genre_id: G4.id)
S25 = Song.create!(name: "Ye", artist: "Burna Boy", url: "https://youtu.be/lPe09eE6Xio", genre_id: G5.id)
S26 = Song.create!(name: "Love Nwantiti", artist: "CKay ft. Joeboy & Kuami Eugene", url: "https://youtu.be/D-YDEyuDxWU", genre_id: G1.id)
S27 = Song.create!(name: "Joro", artist: "Wizkid", url: "https://youtu.be/9YqecbxSr4A", genre_id: G2.id)
S28 = Song.create!(name: "Pana", artist: "Tekno", url: "https://youtu.be/8YhAFBOSk1U", genre_id: G3.id)
S29 = Song.create!(name: "Collabo", artist: "PSquare ft. Don Jazzy", url: "https://youtu.be/tUvF7yj531A", genre_id: G4.id)
S30 = Song.create!(name: "Johnny", artist: "Yemi Alade", url: "https://youtu.be/C_XkTKoDI18", genre_id: G5.id)

S31 = Song.create!(name: "Pepas", artist: "Farruko", url: "https://youtu.be/y8trd3gjJt0", genre_id: G1.id)
S32 = Song.create!(name: "CALLAÍTA", artist: "Bad Bunny", url: "https://youtu.be/acEOASYioGY", genre_id: G2.id)
S33 = Song.create!(name: "Ginza", artist: "J. Balvin", url: "https://youtu.be/zZjSX01P5dE", genre_id: G3.id)
S34 = Song.create!(name: "Eres Mia", artist: "Romeo Santos", url: "https://youtu.be/8iPcqtHoR3U", genre_id: G4.id)
S35 = Song.create!(name: "Obsesión", artist: "Aventura ft. Judy Santos", url: "https://youtu.be/C_XkTKoDI18", genre_id: G5.id)
S36 = Song.create!(name: "Danza Kuduro", artist: "Don Omar ft. Lucenzo", url: "https://youtu.be/C_XkTKoDI18", genre_id: G1.id)
S37 = Song.create!(name: "Suavamente", artist: "Elvis Crespo", url: "https://youtu.be/WPiEbYSF9kE", genre_id: G2.id)
S38 = Song.create!(name: "Chantaje", artist: "Shakira ft. Maluma", url: "https://youtu.be/6Mgqbai3fKo", genre_id: G3.id)
S39 = Song.create!(name: "Bailando", artist: "Enrique Iglesias ft. Descemer Bueno, Gente De Zona", url: "https://youtu.be/NUsoVlDFqZg", genre_id: G4.id)
S40 = Song.create!(name: "El Amante", artist: "Nicky Jam", url: "https://youtu.be/YG2p6XBuSKA", genre_id: G5.id)

S41 = Song.create!(name: "Tequila", artist: "Dan + Shay", url: "https://youtu.be/c4qgqNS_20s", genre_id: G1.id)
S42 = Song.create!(name: "Tennessee Whiskey", artist: "Chris Stapleton", url: "https://youtu.be/4zAThXFOy2c", genre_id: G2.id)
S43 = Song.create!(name: "Blue Ain't Your Color", artist: "Keith Urban", url: "https://youtu.be/SoIKv3xxuMA", genre_id: G3.id)
S44 = Song.create!(name: "As Good As I Once Was", artist: "Toby Keith", url: "https://youtu.be/ldQrapQ4d0Y", genre_id: G4.id)
S45 = Song.create!(name: "Beer Never Broke My Heart", artist: "Luke Combs", url: "https://youtu.be/7Lb9dq-JZFI", genre_id: G5.id)
S46 = Song.create!(name: "Chicken Fried", artist: "Zac Brown Band", url: "https://youtu.be/e4ujS1er1r0", genre_id: G1.id)
S47 = Song.create!(name: "Dirt Road Anthem", artist: "Jason Aldean", url: "https://youtu.be/Lb9q1ScC4cg", genre_id: G2.id)
S48 = Song.create!(name: "This Is How We Roll", artist: "Florida Georgia Line ft. Luke Bryan", url: "https://youtu.be/CbxuXq_981s", genre_id: G3.id)
S49 = Song.create!(name: "Boys 'Round Here", artist: "Blake Shelton ft. Pistol Annies & Friends", url: "https://youtu.be/JXAgv665J14", genre_id: G4.id)
S50 = Song.create!(name: "Before He Cheats", artist: "Carrie Underwood", url: "https://youtu.be/WaSy8yy-mr8", genre_id: G5.id)

S51 = Song.create!(name: "POP!", artist: "NAYEON", url: "https://youtu.be/f6YDKF0LVWw", genre_id: G1.id)
S52 = Song.create!(name: "Dynamite", artist: "BTS", url: "https://youtu.be/gdZLi9oWNZg", genre_id: G2.id)
S53 = Song.create!(name: "GANGNAM STYLE", artist: "PSY", url: "https://youtu.be/9bZkp7q19f0", genre_id: G3.id)
S54 = Song.create!(name: "Dragon", artist: "TEMPEST", url: "https://youtu.be/ZOZDznZYJkU", genre_id: G4.id)
S55 = Song.create!(name: "The Feels", artist: "TWICE", url: "https://youtu.be/f5_wn8mexmM", genre_id: G5.id)
S56 = Song.create!(name: "How You Like That", artist: "BLACKPINK", url: "https://youtu.be/32si5cfrCNc", genre_id: G1.id)
S57 = Song.create!(name: "Thunderous", artist: "Stray Kids", url: "https://youtu.be/EaswWiwMVs8", genre_id: G2.id)
S58 = Song.create!(name: "Oh!", artist: "Girls' Generation", url: "https://youtu.be/TGbwL8kSpEk", genre_id: G3.id)
S59 = Song.create!(name: "Heart Attack", artist: "Exo-K", url: "https://youtu.be/Vxo90RHlGz0", genre_id: G4.id)
S60 = Song.create!(name: "Boys Like You", artist: "ITZY", url: "https://youtu.be/6uZy86ePgO0", genre_id: G5.id)

S61 = Song.create!(name: "Anti-Hero", artist: "Taylor Swift", url: "https://youtu.be/b1kbLwvqugk", genre_id: G1.id)
S62 = Song.create!(name: "New Rules", artist: "Dua Lipa", url: "https://youtu.be/k2qgadSvNyU", genre_id: G2.id)
S63 = Song.create!(name: "Kiss Me More", artist: "Doja Cat ft. SZA", url: "https://youtu.be/0EVVKs6DQLo", genre_id: G3.id)
S64 = Song.create!(name: "Feels", artist: "Calvin Harris ft. Katy Perry, Pharrell Williams, Big Sean", url: "https://youtu.be/ozv4q2ov3Mk", genre_id: G4.id)
S65 = Song.create!(name: "Happier", artist: "Marshmello ft. Bastille", url: "https://youtu.be/m7Bc3pLyij0", genre_id: G5.id)
S66 = Song.create!(name: "Cake By The Ocean", artist: "DNCE", url: "https://youtu.be/vWaRiD5ym74", genre_id: G1.id)
S67 = Song.create!(name: "Rather Be", artist: "Clean Bandit ft. Jess Glynne", url: "https://youtu.be/m-M1AtrxztU", genre_id: G2.id)
S68 = Song.create!(name: "STAY", artist: "The Kid LAROI ft. Justin Bieber", url: "https://youtu.be/kTJczUoc26U", genre_id: G3.id)
S69 = Song.create!(name: "Heat Waves", artist: "Glass Animals", url: "https://youtu.be/mRD0-GxqHVo", genre_id: G4.id)
S70 = Song.create!(name: "Bad Habits", artist: "Ed Sheeran", url: "https://youtu.be/orJSJGHjBLI", genre_id: G5.id)

S71 = Song.create!(name: "Last Christmas", artist: "Wham!", url: "https://youtu.be/E8gmARGvPlI", genre_id: G1.id)
S72 = Song.create!(name: "All I Want Christmas For You", artist: "Mariah Carey", url: "https://youtu.be/yXQViqx6GMY", genre_id: G2.id)
S73 = Song.create!(name: "This Christmas", artist: "Chris Brown", url: "https://youtu.be/b9XNyeeJZ2k", genre_id: G3.id)
S74 = Song.create!(name: "Santa Tell Me", artist: "Ariana Grande", url: "https://youtu.be/nlR0MkrRklg", genre_id: G4.id)
S75 = Song.create!(name: "Mistletoe", artist: "Justin Bieber", url: "https://youtu.be/LUjn3RpkcKY", genre_id: G5.id)
S76 = Song.create!(name: "Snowman", artist: "Sia", url: "https://youtu.be/gset79KMmt0", genre_id: G1.id)
S77 = Song.create!(name: "The Christmas Song", artist: "Nat King Cole", url: "https://youtu.be/wKhRnZZ0cJI", genre_id: G2.id)
S78 = Song.create!(name: "Underneath the Tree", artist: "Kelly Clarkson", url: "https://youtu.be/EM2Fnp_qnE8", genre_id: G3.id)
S79 = Song.create!(name: "Wonderful Christmastime", artist: "Paul McCartney", url: "https://youtu.be/94Ye-3C1FC8", genre_id: G4.id)
S80 = Song.create!(name: "Santa Baby", artist: "Eartha Kitt", url: "https://youtu.be/HTCFi4l3nkY", genre_id: G5.id)

S81 = Song.create!(name: "Turn Down For What", artist: "DJ Snake & Lil Jon", url: "https://youtu.be/HMUDVMiITOU", genre_id: G1.id)
S82 = Song.create!(name: "Bangarang", artist: "SKRILLEX ft. Sirah", url: "https://youtu.be/YJVmu6yttiw", genre_id: G2.id)
S83 = Song.create!(name: "I Can't Stop", artist: "Flux Pavilion", url: "https://youtu.be/3Q9rewnLFYw", genre_id: G3.id)
S84 = Song.create!(name: "#SELFIE", artist: "Chainsmokers", url: "https://youtu.be/kdemFfbS5H0", genre_id: G4.id)
S85 = Song.create!(name: "Where Are Ü Now", artist: "Skrillex & Diplo ft. Justin Bieber", url: "https://youtu.be/nntGTK2Fhb0", genre_id: G5.id)
S86 = Song.create!(name: "Lean On", artist: "Major Lazer & DJ Snake ft. MO", url: "https://youtu.be/YqeW9_5kURI", genre_id: G1.id)
S87 = Song.create!(name: "Wake Me Up", artist: "Avicii", url: "https://youtu.be/IcrbM1l_BoI", genre_id: G2.id)
S88 = Song.create!(name: "Don't You Worry Child", artist: "Swedish House Mafia ft. John Martin", url: "https://youtu.be/1y6smkh6c-0", genre_id: G3.id)
S89 = Song.create!(name: "Clarity", artist: "Zedd ft. Foxes", url: "https://youtu.be/IxxstCcJlsc", genre_id: G4.id)
S90 = Song.create!(name: "We Found Love", artist: "Rihanna ft. Calvin Harris", url: "https://youtu.be/tg00YEETFzg", genre_id: G5.id)

S91 = Song.create!(name: "Thunderstruck", artist: "AC/DC", url: "https://youtu.be/v2AC41dglnM", genre_id: G1.id)
S92 = Song.create!(name: "Eye of the Tiger", artist: "Survivor", url: "https://youtu.be/btPJPFnesV4", genre_id: G2.id)
S93 = Song.create!(name: "Sweet Child O' Mine", artist: "Guns N' Roses", url: "https://youtu.be/1w7OgIMMRc4", genre_id: G3.id)
S94 = Song.create!(name: "You Give Love A Bad Name", artist: "Bon Jovi", url: "https://youtu.be/KrZHPOeOxQQ", genre_id: G4.id)
S95 = Song.create!(name: "Pour Some Sugar On Me", artist: "Def Leppard", url: "https://youtu.be/0UIB9Y4OFPs", genre_id: G5.id)
S96 = Song.create!(name: "Black Betty", artist: "Ram Jam", url: "https://youtu.be/I_2D8Eo15wE", genre_id: G1.id)
S97 = Song.create!(name: "We Will Rock You", artist: "Queen", url: "https://youtu.be/-tJYN-eG1zk", genre_id: G2.id)
S98 = Song.create!(name: "Still Loving You", artist: "Scorpions", url: "https://youtu.be/7pOr3dBFAeY", genre_id: G3.id)
S99 = Song.create!(name: "Faithfully", artist: "Journey", url: "https://youtu.be/OMD8hBsA-RI", genre_id: G4.id)
S100 = Song.create!(name: "Don't Let Me Down", artist: "The Beatles", url: "https://youtu.be/NCtzkaL2t_Y", genre_id: G5.id)

puts "Creating comments ✍️..."

C1 = Comment.create!(user_id: U1.id, song_id: S1.id, description: "This song fire no cap 🔥🔥")
C2 = Comment.create!(user_id: U2.id, song_id: S2.id, description: "🚮😬")
C3 = Comment.create!(user_id: U3.id, song_id: S3.id, description: "Who would've thought this song was gonna be a hit 10+ years ago")
C4 = Comment.create!(user_id: U4.id, song_id: S4.id, description: "Eh... it's okay 🫠")
C5 = Comment.create!(user_id: U1.id, song_id: S5.id, description: "I really like this song! ")
C6 = Comment.create!(user_id: U2.id, song_id: S6.id, description: "This song gives you so much nostalgia")
C7 = Comment.create!(user_id: U3.id, song_id: S7.id, description: "Straight 🗑️💩")
C8 = Comment.create!(user_id: U4.id, song_id: S8.id, description: "🔥🔥🔥")
C9 = Comment.create!(user_id: U1.id, song_id: S9.id, description: "AYOOOO?? THIS SLAPS!!")
C10 = Comment.create!(user_id: U2.id, song_id: S10.id, description: "Always coming out with straight BANGERS! 🔥")

SP1 = SongPlaylist.create(song_id: S1.id, playlist_id: P1.id)
SP2 = SongPlaylist.create(song_id: S2.id, playlist_id: P1.id)
SP3 = SongPlaylist.create(song_id: S3.id, playlist_id: P2.id)
SP4 = SongPlaylist.create(song_id: S4.id, playlist_id: P2.id)
SP5 = SongPlaylist.create(song_id: S5.id, playlist_id: P3.id)
SP6 = SongPlaylist.create(song_id: S1.id, playlist_id: P3.id)
SP7 = SongPlaylist.create(song_id: S6.id, playlist_id: P4.id)
SP8 = SongPlaylist.create(song_id: S1.id, playlist_id: P4.id)
SP9 = SongPlaylist.create(song_id: S2.id, playlist_id: P1.id)
SP10 = SongPlaylist.create(song_id: S10.id, playlist_id: P2.id)

puts "Done seeding!"